"""empty message

Revision ID: a5df15103f0c
Revises: 0f0a9d8adad1
Create Date: 2026-05-06 14:38:16.153032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a5df15103f0c"
down_revision: Union[str, Sequence[str], None] = "0f0a9d8adad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jwt_refresh_tokens", sa.Column("token", sa.String(), nullable=False)
    )
    op.drop_column("jwt_refresh_tokens", "payload")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jwt_refresh_tokens",
        sa.Column(
            "payload", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("jwt_refresh_tokens", "token")
    # ### end Alembic commands ###
