"""update users table

Revision ID: 4ba849b4d4ac
Revises: b40c1f704662
Create Date: 2026-04-08 18:42:57.786189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4ba849b4d4ac"
down_revision: Union[str, Sequence[str], None] = "b40c1f704662"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=30), nullable=False)
    )
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "firstname",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
