"""upgrade users table (column)

Revision ID: b3a4a492e10a
Revises: 4ba849b4d4ac
Create Date: 2026-04-08 18:51:27.651373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b3a4a492e10a"
down_revision: Union[str, Sequence[str], None] = "4ba849b4d4ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=30), nullable=False)
    )
    op.drop_column("users", "lastname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "lastname",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###
