"""empty message

Revision ID: 1ceab63da3df
Revises: b3a4a492e10a
Create Date: 2026-04-09 10:44:36.490007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1ceab63da3df"
down_revision: Union[str, Sequence[str], None] = "b3a4a492e10a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=35),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=35),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
