"""fix session_is type

Revision ID: 924bd76f5b18
Revises: 2d3dc36f52ae
Create Date: 2026-04-09 13:53:31.512074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "924bd76f5b18"
down_revision: Union[str, Sequence[str], None] = "2d3dc36f52ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "session_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "session_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
