"""empty message

Revision ID: e5033f63b3fc
Revises: da104e663480
Create Date: 2026-04-11 11:25:05.933328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e5033f63b3fc"
down_revision: Union[str, Sequence[str], None] = "da104e663480"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("sessions_user_id_fkey"), "sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("sessions_user_id_fkey"), "sessions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
