"""empty message

Revision ID: 9869e81ab539
Revises: 6ba5bae988c0
Create Date: 2026-04-17 14:12:35.645470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9869e81ab539"
down_revision: Union[str, Sequence[str], None] = "6ba5bae988c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("admin", "user", name="roleenum"),
            server_default=sa.text("'user'::roleenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("admins")
    # ### end Alembic commands ###
