"""empty message

Revision ID: 30a18a273fe4
Revises: f53e9d2346cf
Create Date: 2026-04-18 10:59:10.598187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "30a18a273fe4"
down_revision: Union[str, Sequence[str], None] = "f53e9d2346cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "admins", ["user_id"])
    op.create_unique_constraint(None, "post_query", ["post_id"])
    op.create_unique_constraint(None, "sessions", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="unique")
    op.drop_constraint(None, "post_query", type_="unique")
    op.drop_constraint(None, "admins", type_="unique")
    # ### end Alembic commands ###
